# TCL File Generated by Component Editor 25.3
# Tue Aug 18 16:59:54 EDT 2026
# DO NOT MODIFY


# 
# sa_avalon_agent "sa_avalon_agent" v1.0
# ddi 2026.08.18.16:59:54
# 
# 

# 
# request TCL package from ACDS 25.3
# 
package require -exact qsys 25.3


# 
# module sa_avalon_agent
# 
set_module_property DESCRIPTION ""
set_module_property NAME sa_avalon_agent
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property AUTHOR ddi
set_module_property ICON_PATH null
set_module_property DISPLAY_NAME sa_avalon_agent
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false
set_module_property DISPLAY_ICON ""


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sa_avalon_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sa_avalon_pkg.vhd VHDL PATH src/packages/sa_avalon_pkg.vhd
add_fileset_file sa_csr.vhd VHDL PATH src/rtl/sa_csr.vhd
add_fileset_file sa_fifo.vhd VHDL PATH src/rtl/sa_fifo.vhd
add_fileset_file sa_result_capture.vhd VHDL PATH src/rtl/sa_result_capture.vhd
add_fileset_file sa_skew_fsm.vhd VHDL PATH src/rtl/sa_skew_fsm.vhd
add_fileset_file systolic_pe.vhd VHDL PATH src/rtl/systolic_pe.vhd
add_fileset_file sa_avalon_top.vhd VHDL PATH src/top/sa_avalon_top.vhd TOP_LEVEL_FILE
add_fileset_file systolic_array.vhd VHDL PATH src/top/systolic_array.vhd
add_fileset_file systolic_pe_wrap.vhd VHDL PATH src/top/systolic_pe_wrap.vhd


# 
# parameters
# 
add_parameter SIGNED_ARITH BOOLEAN true
set_parameter_property SIGNED_ARITH DEFAULT_VALUE true
set_parameter_property SIGNED_ARITH DISPLAY_NAME SIGNED_ARITH
set_parameter_property SIGNED_ARITH UNITS None
set_parameter_property SIGNED_ARITH AFFECTS_GENERATION false
set_parameter_property SIGNED_ARITH HDL_PARAMETER true
set_parameter_property SIGNED_ARITH TRANSFORM_PARAMETER false
set_parameter_property SIGNED_ARITH EXPORT true
set_parameter_property SIGNED_ARITH READ_ONLY false
add_parameter IN_FIFO_DEPTH NATURAL 32
set_parameter_property IN_FIFO_DEPTH DEFAULT_VALUE 32
set_parameter_property IN_FIFO_DEPTH DISPLAY_NAME IN_FIFO_DEPTH
set_parameter_property IN_FIFO_DEPTH UNITS None
set_parameter_property IN_FIFO_DEPTH ALLOWED_RANGES 0:2147483647
set_parameter_property IN_FIFO_DEPTH AFFECTS_GENERATION false
set_parameter_property IN_FIFO_DEPTH HDL_PARAMETER true
set_parameter_property IN_FIFO_DEPTH TRANSFORM_PARAMETER false
set_parameter_property IN_FIFO_DEPTH EXPORT true
set_parameter_property IN_FIFO_DEPTH READ_ONLY false
add_parameter OUT_FIFO_DEPTH NATURAL 64
set_parameter_property OUT_FIFO_DEPTH DEFAULT_VALUE 64
set_parameter_property OUT_FIFO_DEPTH DISPLAY_NAME OUT_FIFO_DEPTH
set_parameter_property OUT_FIFO_DEPTH UNITS None
set_parameter_property OUT_FIFO_DEPTH ALLOWED_RANGES 0:2147483647
set_parameter_property OUT_FIFO_DEPTH AFFECTS_GENERATION false
set_parameter_property OUT_FIFO_DEPTH HDL_PARAMETER true
set_parameter_property OUT_FIFO_DEPTH TRANSFORM_PARAMETER false
set_parameter_property OUT_FIFO_DEPTH EXPORT true
set_parameter_property OUT_FIFO_DEPTH READ_ONLY false


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""
set_interface_property clock IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clock SV_INTERFACE_TYPE ""
set_interface_property clock SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""
set_interface_property reset IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property reset SV_INTERFACE_TYPE ""
set_interface_property reset SV_INTERFACE_MODPORT_TYPE ""

add_interface_port reset rst_n reset_n Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressGroup 0
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave bridgedAddressOffset ""
set_interface_property avalon_slave bridgesToMaster ""
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave minimumResponseLatency 1
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave transparentBridge false
set_interface_property avalon_slave waitrequestAllowance 0
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave dfhFeatureGuid 0
set_interface_property avalon_slave dfhGroupId 0
set_interface_property avalon_slave dfhParameterId ""
set_interface_property avalon_slave dfhParameterName ""
set_interface_property avalon_slave dfhParameterVersion ""
set_interface_property avalon_slave dfhParameterData ""
set_interface_property avalon_slave dfhParameterDataLength ""
set_interface_property avalon_slave dfhFeatureMajorVersion 0
set_interface_property avalon_slave dfhFeatureMinorVersion 0
set_interface_property avalon_slave dfhFeatureId 35
set_interface_property avalon_slave dfhFeatureType 3
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""
set_interface_property avalon_slave IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property avalon_slave SV_INTERFACE_TYPE ""
set_interface_property avalon_slave SV_INTERFACE_MODPORT_TYPE ""

add_interface_port avalon_slave avs_address address Input 4
add_interface_port avalon_slave avs_read read Input 1
add_interface_port avalon_slave avs_readdata readdata Output 32
add_interface_port avalon_slave avs_write write Input 1
add_interface_port avalon_slave avs_writedata writedata Input 32
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyAllowance 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""
set_interface_property avalon_streaming_source IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property avalon_streaming_source SV_INTERFACE_TYPE ""
set_interface_property avalon_streaming_source SV_INTERFACE_MODPORT_TYPE ""

add_interface_port avalon_streaming_source aso_data data Output 32
add_interface_port avalon_streaming_source aso_valid valid Output 1
add_interface_port avalon_streaming_source aso_ready ready Input 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock
set_interface_property avalon_streaming_sink associatedReset reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyAllowance 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""
set_interface_property avalon_streaming_sink IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property avalon_streaming_sink SV_INTERFACE_TYPE ""
set_interface_property avalon_streaming_sink SV_INTERFACE_MODPORT_TYPE ""

add_interface_port avalon_streaming_sink asi_data data Input 32
add_interface_port avalon_streaming_sink asi_valid valid Input 1
add_interface_port avalon_streaming_sink asi_ready ready Output 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""
set_interface_property interrupt_sender IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property interrupt_sender SV_INTERFACE_TYPE ""
set_interface_property interrupt_sender SV_INTERFACE_MODPORT_TYPE ""

add_interface_port interrupt_sender irq irq Output 1

